### model
model_name_or_path: meta-llama/Llama-2-7b-chat-hf

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: llama-2-7b-pref-phs-dataset
template: llama2
cutoff_len: 2048
overwrite_cache: false
preprocessing_num_workers: 16

### output
output_dir: saves/llama2-7b/phs/dpo_bs_8
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 1
learning_rate: 5.0e-5
num_train_epochs: 6.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 1000
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 500

### wandb
report_to: wandb
run_name: llama-2-7b-phs-dpo-bs-8 # optional